# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: my-personal-computer

steps:
- task: CmdLine@2
  inputs:
    script: 'chmod 777 gradlew'
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'Manoj'
    cliInstallationRepo: 'jfrog-cli-v2'
    installExtractors: true
    extractorsInstallationRepo: 'extractors'
- task: JFrogGradle@1
  inputs:
    gradleBuildFile: 'build.gradle.kts'
    options: '-d'
    tasks: 'artifactoryPublish'
    artifactoryResolverService: 'Manoj'
    sourceRepo: 'manoj-virtual'
    artifactoryDeployerService: 'Manoj'
    targetRepo: 'manoj-local'
    usesPlugin: true
    useWrapper: true
    javaHomeOption: 'JDKVersion'